### ISSUE TITLE
Rogue's Den + Sharks = Crash

### ISSUE THREAD

**Issue by Mithril-Leaf** [2006rebotted/2006rebotted#365] opened 2020-01-17 20:29 UTC
If you have raw sharks in your inventory in the Rogue's Den specifically, it is prone to locking up the game client, preventing any player interactions. You can still open menus in Parabot, but cannot interact with the game world in any way. It happens very consistently if you bank in the Rogue's Den, take out a full inventory of Raw Sharks with Cooking Gauntlets on, then click on the settings menu immediately.

**Comment by mrextremez** [comment] 2020-01-18 10:20
Good find, will look into that

**Comment by mrextremez** [comment] 2020-01-21 07:26
Does it happen with fish other than shark?

**Comment by dginovker** [comment] 2020-08-05 18:35
Can't reproduce, closing unless it occurs again

**Closed by dginovker** 2020-08-05 18:35 UTC
